### ISSUE TITLE
Crashes on 1.19

### ISSUE THREAD

**Issue by joshuacrotts** [LimeAppleBoat/EndGoblinTraders#15]
Not really sure what's causing the problem here - I have the appropriate mods listed on the CurseForge page...

```
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'endgoblintraders'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:49)
	at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.createDefault(Toml4jConfigSerializer.java:84)
	at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:78)
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
	at com.jab125.egt.EGobT.onInitialize(EGobT.java:42)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:47)
	... 23 more
Caused by: java.lang.NoSuchFieldError: field_25407
	at com.jab125.egt.config.EndGoblinTradersConfig$EndGoblinTrader.<init>(EndGoblinTradersConfig.java:28)
	at com.jab125.egt.config.EndGoblinTradersConfig.<init>(EndGoblinTradersConfig.java:17)
	... 29 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.18.9-arch1-1
	Java Version: 17.0.3, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1488092624 bytes (1419 MiB) / 4408213504 bytes (4204 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU104 [GeForce RTX 2070 SUPER]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12069.10
	Virtual memory used (MB): 6914.59
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 211.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.3.0+0
		betteradvancements: Better Advancements 0.2.1.134
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterf3: BetterF3 1.3.1
		blossom: Blossom 1.0.5
		bookshelf: Bookshelf 14.0.5
		byg: Oh The Biomes You'll Go 2.0.0.5
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cleancut: CleanCut 1.19-5.0-fabric
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.72
		clumps: Clumps 9.0.0+3
		controlling: Controlling For Fabric 10.0+1
		cookingforblockheads: Cooking for Blockheads 13.1.2
		croptopia: Croptopia 2.0.6
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkpaintings: DarkPaintings 11.0.2
		darkutils: DarkUtilities 11.0.2
		ecologics: Ecologics 2.1.1
		enchdesc: EnchantmentDescriptions 11.0.5
		endgoblintraders: End Goblin Traders 1.4.4
		essential: Essential 3160+feature-fabric-1.19
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric: Fabric API 0.56.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+82552130a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.24+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.2+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.9+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.6+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.4+db8596f1a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmingforblockheads: Farming for Blockheads 11.0.1
		foodplusid: Food+ 1.4.1
		fpsreducer: FPS Reducer 1.19-2.0.1
		ftbbackups2: FTB Backups 2 1.0.12
		ftbchunks: FTB Chunks 1900.3.7-build.154
		ftblibrary: FTB Library 1900.3.7-build.131
		ftbteams: FTB Teams 1900.2.7-build.56
		ftbultimine: FTB Ultimine 1900.3.4-build.58
		goblintraders: Goblin Traders 1.5.2
		indium: Indium 1.0.6+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests: Restocked 3.0.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.0.0.206
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lithium: Lithium 0.8.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.3
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		more-axolotls: More Axolotls 1.0.2
		moreberries: More Berries 1.5.1
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		myloot: myLoot 3.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		phosphor: Phosphor 0.8.1
		repurposed_structures: Repurposed Structures 6.0.7+1.19
			midnightlib: MidnightLib 0.5.2
		right-click-harvest: Right-Click-Harvest 1.2.0
		simple_backpack: SimpleBackpack 1.3.16
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		spawnermod: Enhanced Mob Spawners 1.1.4
		spoornpacks: SpoornPacks 4.3.1-1.19
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		terrablender: TerraBlender 2.0.0.113
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		toms_storage: Tom's Simple Storage Mod 1.3.5
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		trinkets: Trinkets 3.4.0
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.6+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.1+1.19
		waystones: Waystones 11.0.1
		wthit: wthit 5.4.3
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
```

**Comment by Jab125** [comment]
End Goblin Traders currently does not support 1.19, support is expected to come in the coming days.

**Comment by Sunconure11** [comment]
@Jab125 Then you might have a problem.

https://www.curseforge.com/minecraft/mc-mods/end-goblin-traders-fabric/files/3682602

Latest build is listed as 1.19 compatible

**Comment by Jab125** [comment]
It's compatible with 1.19 deep dark experimental snapshot 1
