### ISSUE TITLE
Crash upon loading game

### ISSUE THREAD

**Issue by RechercheRaptor** [LimeAppleBoat/EndGoblinTraders#23]
After hitting 'play' in the launcher, after waiting about a minute, the launcher reopens with a crash message that an entry point could not be found due to something with End Goblin Traders. I am on version 1.19.2, Fabric 0.14.18, and End Goblin Traders 1.5.1.

I am using quite a few other mods, which I will list below the crash report. I wanted to make a test profile that only had End Goblin Traders, but when I made a new 1.19.2 profile and went to add new content I couldn't find it in CurseForge's library.

This is the full crash message:
"---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-04-28 19:04:39
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'endgoblintraders'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/jab125/util/tradehelper/TradeManager
	at com.jab125.egt.EGobT.onInitialize(EGobT.java:73)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.jab125.util.tradehelper.TradeManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 13.2.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1797686960 bytes (1714 MiB) / 3923771392 bytes (3742 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 14155.94
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 7218.13
	JVM Flags: 2 total; -Xmx4096m -Xms256m
	Fabric Mods: 
		adorn: Adorn 3.8.2+1.19.2
		alloy_forgery: Alloy Forgery 2.0.20+1.19
		armorposer: Armor Poser 1.2.2
		badpackets: Bad Packets 0.2.1
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		betternether: Better Nether 7.1.3
		bettertridents: Better Tridents 4.0.2
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		bygonenether: Bygone Nether 1.2.2
			midnightlib: MidnightLib 1.0.0
			porting_lib: Porting Lib 2.1.706+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.706+1.19.2
					mm: Manningham Mills 2.3
					porting_lib_entity: Porting Lib Entity 2.1.706+1.19.2
					porting_lib_fake_players: Porting Lib Fake Players 2.1.706+1.19.2
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.706+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.706+1.19.2
					porting_lib_models: Porting Lib Models 2.1.706+1.19.2
						porting_lib_obj_loader: Porting Lib Obj Loader 2.1.706+1.19.2
							porting_lib_model_loader: Porting Lib Model Loader 2.1.706+1.19.2
						porting_lib_transfer: Porting Lib Transfer 2.1.706+1.19.2
							porting_lib_extensions: Porting Lib Extensions 2.1.706+1.19.2
								porting_lib_accessors: Porting Lib Accessors 2.1.706+1.19.2
								porting_lib_attributes: Porting Lib Attributes 2.1.706+1.19.2
									porting_lib_constants: Porting Lib Constants 2.1.706+1.19.2
								porting_lib_common: Porting Lib Common 2.1.706+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.706+1.19.2
		carpeted: Carpeted 1.19.2-1.4
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.53
		configured: Configured 2.0.0
		dragondropselytra: Dragon Drops Elytra 3.0
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.4.2_1
		emi: EMI 0.7.3+1.19.2
		endgoblintraders: End Goblin Traders 1.5.1
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.18
		forgeconfigapiport: Forge Config API Port 4.2.11
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		goblintraders: Goblin Traders 1.8.1
		graveyard_biomes: The Graveyard Biomes 1.6
			omega-config: OmegaConfig 1.2.2-1.18.1
		java: OpenJDK 64-Bit Server VM 17
		mclegends: MC Legends Mod 1.0
		minecraft: Minecraft 1.19.2
		mob_catcher: Mob Catcher 1.2.15
		moonlight: Moonlight 1.19.2-2.2.31
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.2
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		puzzleslib: Puzzles Lib 4.4.0
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		structory_towers: Structory: Towers 1.0.0
		supplementaries: Supplementaries 1.19.2-2.3.5
		suppsquared: Supplementaries Squared 1.19.2-1.0.14
		terrablender: TerraBlender 2.0.1.136
		terrarianslimes: Terrarian Slimes 1.3.1-BETA+1.19
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		treeharvester: Tree Harvester 8.0
		trinkets: Trinkets 3.4.2
		wthit: wthit 5.15.2
		xaerominimap: Xaero's Minimap 23.4.0
	Launched Version: fabric-loader-0.14.18-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>"

Other mods:
Adorn
Alloy Forgery
Armor Poser
bad packets
BClib
Better Tridents
Better End
Better Nether
Bygone Nether (Fabric)
Carpeted Stairs & Slabs
Cloth Config API (Fabric)
Collective
Configured (Fabric)
Dragon Drops Elytra
Dramatic Doors
EMI
End Goblin Traders
Fabric API
Fabric Language Kotlin
Forge Config API Port
Gecko Lib
Goblin Traders (Fabric)
Legends Features
Mob Catcher
Moonlight Lib
Mythic Metals
Mythic Metals Decorative
Mythic Mounts
Oh The Biomes You'll Go
owo lib
Patchouli (Fabric/Quilt)
Puzzles Lib (Forge & Fabric)
Stoneholm, Underground Villages
Structory
Structory: Towers
Supplementaries
Supplementaries Squared
Terrablender (Fabric)
Terrarian Slimes
The Graveyard Biomes
ThonkUtil
Tree Harvester
Trinkets (Fabric)
WTHIT
Xaero's Minimap

**Comment by Jab125** [comment]
try using 1.5.2
